Readme.md update
wilt00/finals-dashboard-ts pull request #6
Opened 2019-05-08 16:37 UTC by bmiddha

- added screenshot
- added port change info

2019-05-09 02:45 UTC, bmiddha commented
now uses Moment.format instead of template strings to update countdowns.
looks cleaner

2019-05-09 16:39 UTC, bmiddha commented
added contributors to footer

2019-05-10 00:36 UTC, bmiddha commented
added support for registrar api

2019-05-10 04:05 UTC, bmiddha commented
last commit has introduced some problems
Building and Location, AM PM irregulartities (can be fixed with regex from scraper.ts)

2019-05-26 18:06 UTC, wilt00 requested changes

2019-05-26 18:06 UTC, wilt00 commented on src/getFinals.ts
> +    const examData: ExamAPI = await (await fetch("https://registrar.uic.edu/assets/scripts/finals-initial-query.php?term=220191")).json();
Can we not hard code the term here?

2019-05-26 18:06 UTC, wilt00 commented on frontend/main.scss
> +}
What about this requires SASS?

2019-05-26 18:06 UTC, wilt00 commented on src/getFinals.ts
> +    });
This is not equivalent to the current behavior - doesn't deduplicate undergrad and grad finals, for example.

2019-05-26 18:06 UTC, wilt00 commented on src/getFinals.ts
> +            examInfo.finalStart     = new Date(element.day + " 2019 " + element.time.split(" ")[0] + " " + element.time.split(" ")[3] + " CST").toISOString();
Year hard coded

2019-05-26 18:06 UTC, wilt00 commented on src/getFinals.ts
> +            console.log(element.day + " 2019 " + element.time.split(" ")[2] + " " + element.time.split(" ")[3] + " CST");
This logic is repeated at least 3x - should spin out into a function

2019-12-13 19:13 UTC, bmiddha commented
Closing. No longer working on this.
New project: https://github.com/bmiddha/final-countdown

2019-12-13 19:13 UTC, closed without merging